### ISSUE TITLE
SKOS hierarchie [-7]

### ISSUE THREAD

**Issue by skodapetr** [DuongXuanAnh/NDBI046_Datave_Inzenyrstvi#3]
Úkolem bylo vytvořit SKOS hierarchii. Tedy využít broader/narrower nebo broadMatch/narrowMatch pro propojení okresů a krajů na úrovni instancí (okres je v kraji).

Současně koukněte na co má ukazovat inScheme (ConceptScheme) a to váš vlastní.

Mapování na cizí koncepty není na škodu, ale v tomto případě je cílem vytvořit si vlatní hierarchii.

**Comment by DuongXuanAnh** [comment]
Přidal jsem tam broader/narrower pro propojení. Ale nejsem si jistý zda to odpovídá k požadavku.
