### ISSUE TITLE
Using self-signed certificate [-3]

### ISSUE THREAD

**Issue by skodapetr** [DuongXuanAnh/NDBI046_Datave_Inzenyrstvi#4]

**Comment by DuongXuanAnh** [comment]
Trochu nechápu? Já nemám používat svůj vlastní certificate? Ale mám používat Váš? Jestli ano, tak kde ho můžu najít?

**Comment by DuongXuanAnh** [comment]
Už jsem použil podepsaný certifikát od Vás
